Bug Fixes #20
PixelogicDev/FocusBlock pull request #23
Opened 2018-07-09 18:26 UTC by frubesss

- [x] User can enter blank title:
Fixed by trimming the inserted value and seeing if it contains any text, fairly simple.

- [x] User can enter custom unchecked time. (e.g., -10, 0, 111111111111111111111111):
Fixed by adding basic HTML form min and max values. The only two downsides I see to this is the form validation style now looks completely different to the style you originally created potentially causing confusion and the max value the user can insert has been restricted to 1 year, not sure how you feel about that but seems sensible in the grand scheme of things.

- [x] When editing focus block title. pressing enter defaults to delete prompt. bad UX:
Another simple fix, both the delete and cancel buttons did not have a type attribute causing the form to default to the first button in the form when the user pressed the enter key.

- [x] When time is too great, countdown timer does not work when clicking gets focused - This has been inherently fixed via the 2nd bug I spoke about above.

Thanks

2018-07-09 19:47 UTC, adilanchian requested changes
This will be a fantastic fix and is greatly appreciated :). Other than the comments noted, I have one more request to ask of you:

1. I will be creating a branch `release-1.0.1`, can you change the PR to be merged into that branch please? Once we get all the release-1.0.1 fixes in, I will go ahead and merge to `master`!

Fantastic work and thanks again!

2018-07-09 19:47 UTC, adilanchian commented on focus-block/src/Components/BlockForm/BlockForm.js
> +								max="525600"
Can we change max to be 1,440? That should be max of 24 hours I think that is well over the amount of time haha.

2018-07-09 19:47 UTC, adilanchian commented on focus-block/src/Components/BlockForm/BlockForm.js
> +                const EMPTY_FIELD_CHECK = title.trim() === "";
Super nit picky:

Can we change the string check to be single quotes? I have used single quotes across the entire app!

2018-07-09 19:47 UTC, adilanchian commented on focus-block/src/Components/BlockForm/BlockForm.js
> +                const EMPTY_FIELD_CHECK = title.trim() === "";
2nd Note:

To keep the error style the same how about creating a helper function that checks to see if the title is valid or not based off of these params? So for example:
```
titleIsValid = (title) => {
    return (title.trim() !== '' ? 'valid' : 'Title cannot be empty');
}

...

titleValid = self.isTitleValid(event.target.value);
```
Let me know your thoughts on this!

2018-07-09 20:25 UTC, frubesss commented on focus-block/src/Components/BlockForm/BlockForm.js
> +                const EMPTY_FIELD_CHECK = title.trim() === "";
Hi Adilan, thanks for taking the time to look at this its much appreciated.

Although for the 2nd note that you have described I don't quite understand.

The error style for the title length works using the style you have implemented (Red text underneath the field).

It was the min and max lengths on the custom input field that doesn't use the validation style you have implemented, it just uses the browser tooltips to highlight the validation issue to the user.

Would you like me to implement the min and max length check using your validation function?

Thanks again.

2018-07-09 20:40 UTC, adilanchian commented on focus-block/src/Components/BlockForm/BlockForm.js
> +                const EMPTY_FIELD_CHECK = title.trim() === "";
Hey @frubesss !

Of course, I appreciate you taking the time to contribute!

Oh my bad! Yes please use that same concept to write a validation method for the time selector. If you can find a way to create one function for ALL the checks, that would be super clean as well :)

2018-07-13 12:20 UTC, adilanchian commented
Closing this as we are going to branch release-1.0.1

2018-07-13 12:20 UTC, closed without merging